#pragma once
#include "Profiling.hpp"

#ifdef BEY_PROFILING_ALL_ENABLED
#ifndef SYMBOL_ENGINE_PROFILING_ENABLED
#define SYMBOL_ENGINE_PROFILING_ENABLED
#endif
#ifndef VIDEO_CAPTURE_PROFILING_ENABLED
#define VIDEO_CAPTURE_PROFILING_ENABLED
#endif
#ifndef DMA_PROFILING_ENABLED
#define DMA_PROFILING_ENABLED
#endif
#ifndef IMU_PROFILING_ENABLED
#define IMU_PROFILING_ENABLED
#endif
#ifndef MATCHING_ALGO_PROFILING_ENABLED
#define MATCHING_ALGO_PROFILING_ENABLED
#endif
#ifndef MOSSE_PROFILING_ENABLED
#define MOSSE_PROFILING_ENABLED
#endif
#ifndef VIDEO_ENCODING_PROFILING_ENABLED
#define VIDEO_ENCODING_PROFILING_ENABLED
#endif
#ifndef ALGO_PROFILING_ENABLED
#define ALGO_PROFILING_ENABLED
#endif
#ifndef RENDERING_PROFILING_ENABLED
#define RENDERING_PROFILING_ENABLED
#endif
#endif

#ifdef  SYMBOL_ENGINE_PROFILING_ENABLED
#define SYMBOL_ENGINE_PROFILE_SCOPE(name, color) PROFILE_CATEGORIZED_SCOPE(name, color, Profiling::PROFILING_CATEGORY_SYMBOL_ENGINE)
#define SYMBOL_ENGINE_PROFILE_SET_MARK(name, color)  PROFILE_SET_CATEGORIZED_MARK(name, color, Profiling::PROFILING_CATEGORY_SYMBOL_ENGINE)
#define SYMBOL_ENGINE_PROFILE_PUSH_RANGE(name, color) PROFILE_PUSH_CATEGORIZED_RANGE(name, color, Profiling::PROFILING_CATEGORY_SYMBOL_ENGINE)
#define SYMBOL_ENGINE_PROFILE_POP_RANGE PROFILE_POP_RANGE
#else
#define SYMBOL_ENGINE_PROFILE_SET_MARK(name, color)
#define SYMBOL_ENGINE_PROFILE_SCOPE(name, color) 
#define SYMBOL_ENGINE_PROFILE_SCOPE(name, color)
#define SYMBOL_ENGINE_PROFILE_PUSH_RANGE(name, color) 
#define SYMBOL_ENGINE_PROFILE_POP_RANGE()
#endif

#ifdef  VIDEO_CAPTURE_PROFILING_ENABLED
#define VIDEO_CAPTURE_PROFILE_SCOPE(name, color) PROFILE_CATEGORIZED_SCOPE(name, color, Profiling::PROFILING_CATEGORY_VIDEO_CAPTURE)
#define VIDEO_CAPTURE_PROFILE_SET_MARK(name, color)  PROFILE_SET_CATEGORIZED_MARK(name, color, Profiling::PROFILING_CATEGORY_VIDEO_CAPTURE)
#define VIDEO_CAPTURE_PROFILE_PUSH_RANGE(name, color) PROFILE_PUSH_CATEGORIZED_RANGE(name, color, Profiling::PROFILING_CATEGORY_VIDEO_CAPTURE)
#define VIDEO_CAPTURE_PROFILE_POP_RANGE PROFILE_POP_RANGE
#else   
#define VIDEO_CAPTURE_PROFILE_SCOPE(name, color) 
#define VIDEO_CAPTURE_PROFILE_SCOPE(name, color)
#define VIDEO_CAPTURE_PROFILE_PUSH_RANGE(name, color) 
#define VIDEO_CAPTURE_PROFILE_POP_RANGE()
#endif
        
#ifdef  DMA_PROFILING_ENABLED
#define DMA_PROFILE_SCOPE(name, color) PROFILE_CATEGORIZED_SCOPE(name, color, Profiling::PROFILING_CATEGORY_DMA)
#define DMA_PROFILE_SET_MARK(name, color) PROFILE_SET_CATEGORIZED_MARK(name, color, Profiling::PROFILING_CATEGORY_DMA)
#define DMA_PROFILE_PUSH_RANGE(name, color) PROFILE_PUSH_CATEGORIZED_RANGE(name, color, Profiling::PROFILING_CATEGORY_DMA)
#define DMA_PROFILE_POP_RANGE PROFILE_POP_RANGE
#define DMA_PROFILE_START_UNTHREADED_RANGE(name, color) PROFILE_START_CATEGORIZED_UNTHREADED_RANGE(name,color, Profiling::PROFILING_CATEGORY_DMA)
#define DMA_PROFILE_END_UNTHREADED_RANGE(id) Profiling::EndUnthreadedRange(id)
#else   
#define DMA_PROFILE_SCOPE(name, color) 
#define DMA_PROFILE_SET_MARK(name, color)
#define DMA_PROFILE_PUSH_RANGE(name, color) 
#define DMA_PROFILE_POP_RANGE()
#define DMA_PROFILE_START_UNTHREADED_RANGE(name, color) 
#define DMA_PROFILE_END_UNTHREADED_RANGE()
#endif

#ifdef  IMU_PROFILING_ENABLED
#define IMU_PROFILE_SCOPE(name, color) PROFILE_CATEGORIZED_SCOPE(name, color, Profiling::PROFILING_CATEGORY_IMU)
#define IMU_PROFILE_SET_MARK(name, color) PROFILE_SET_CATEGORIZED_MARK(name, color, Profiling::PROFILING_CATEGORY_IMU)
#define IMU_PROFILE_PUSH_RANGE(name, color) PROFILE_PUSH_CATEGORIZED_RANGE(name, color, Profiling::PROFILING_CATEGORY_IMU)
#define IMU_PROFILE_POP_RANGE PROFILE_POP_RANGE
#define IMU_PROFILE_START_UNTHREADED_RANGE(name, color) PROFILE_START_CATEGORIZED_UNTHREADED_RANGE(name,color, Profiling::PROFILING_CATEGORY_IMU)
#define IMU_PROFILE_END_UNTHREADED_RANGE(id) Profiling::EndUnthreadedRange(id)
#else   
#define IMU_PROFILE_SCOPE(name, color) 
#define IMU_PROFILE_SET_MARK(name, color)
#define IMU_PROFILE_PUSH_RANGE(name, color) 
#define IMU_PROFILE_POP_RANGE()
#define IMU_PROFILE_START_UNTHREADED_RANGE(name, color) 
#define IMU_PROFILE_END_UNTHREADED_RANGE()
#endif


#ifdef MATCHING_ALGO_PROFILING_ENABLED
#define MATCHING_ALGO_PROFILE_SCOPE(name, color) PROFILE_CATEGORIZED_SCOPE(name, color, Profiling::PROFILING_CATEGORY_MATCHING_ALGO)
#define MATCHING_ALGO_PROFILE_SET_MARK(name, color) PROFILE_SET_CATEGORIZED_MARK(name, color, Profiling::PROFILING_CATEGORY_MATCHING_ALGO)
#define MATCHING_ALGO_PROFILE_PUSH_RANGE(name, color) PROFILE_PUSH_CATEGORIZED_RANGE(name, color, Profiling::PROFILING_CATEGORY_MATCHING_ALGO)
#define MATCHING_ALGO_PROFILE_POP_RANGE PROFILE_POP_RANGE
#define MATCHING_ALGO_PROFILE_START_UNTHREADED_RANGE(name, color) PROFILE_START_CATEGORIZED_UNTHREADED_RANGE(name,color, Profiling::PROFILING_CATEGORY_MATCHING_ALGO)
#define MATCHING_ALGO_PROFILE_END_UNTHREADED_RANGE(id) Profiling::EndUnthreadedRange(id)
#define MATCHING_ALGO_PROFILE_UNTHREADED_SCOPE(name, color) PROFILE_CATEGORIZED_UNTHREADED_SCOPE(name, color, Profiling::PROFILING_CATEGORY_MATCHING_ALGO)

#else
#define MATCHING_ALGO_PROFILE_SCOPE(name, color) 
#define MATCHING_ALGO_PROFILE_SET_MARK(name, color)
#define MATCHING_ALGO_PROFILE_PUSH_RANGE(name, color) 
#define MATCHING_ALGO_PROFILE_POP_RANGE()
#define MATCHING_ALGO_PROFILE_START_UNTHREADED_RANGE(name, color) 0
#define MATCHING_ALGO_PROFILE_END_UNTHREADED_RANGE(id) id
#define MATCHING_ALGO_PROFILE_UNTHREADED_SCOPE(name, color)
#endif

#ifdef  MOSSE_PROFILING_ENABLED
#define MOSSE_PROFILE_SCOPE(name, color) PROFILE_CATEGORIZED_SCOPE(name, color, Profiling::PROFILING_CATEGORY_MOSSE)
#define MOSSE_PROFILE_SET_MARK(name, color) PROFILE_SET_CATEGORIZED_MARK(name, color, Profiling::PROFILING_CATEGORY_MOSSE)
#define MOSSE_PROFILE_PUSH_RANGE(name, color) PROFILE_PUSH_CATEGORIZED_RANGE(name, color, Profiling::PROFILING_CATEGORY_MOSSE)
#define MOSSE_PROFILE_POP_RANGE PROFILE_POP_RANGE
#define MOSSE_PROFILE_START_UNTHREADED_RANGE(name, color) PROFILE_START_CATEGORIZED_UNTHREADED_RANGE(name,color, Profiling::PROFILING_CATEGORY_MOSSE)
#define MOSSE_PROFILE_END_UNTHREADED_RANGE(id) Profiling::EndUnthreadedRange(id)
#define MOSSE_PROFILE_UNTHREADED_SCOPE(name, color) PROFILE_CATEGORIZED_UNTHREADED_SCOPE(name, color, Profiling::PROFILING_CATEGORY_MOSSE)

#else
#define MOSSE_PROFILE_SCOPE(name, color) 
#define MOSSE_PROFILE_SET_MARK(name, color)
#define MOSSE_PROFILE_PUSH_RANGE(name, color) 
#define MOSSE_PROFILE_POP_RANGE()
#define MOSSE_PROFILE_START_UNTHREADED_RANGE(name, color) 0
#define MOSSE_PROFILE_END_UNTHREADED_RANGE(id) id
#define MOSSE_PROFILE_UNTHREADED_SCOPE(name, color)
#endif

#ifdef  VIDEO_ENCODING_PROFILING_ENABLED
#define VIDEO_ENCODING_PROFILE_SCOPE(name, color) PROFILE_CATEGORIZED_SCOPE(name, color, Profiling::PROFILING_CATEGORY_VIDEO_ENCODING)
#define VIDEO_ENCODING_PROFILE_SET_MARK(name, color) PROFILE_SET_CATEGORIZED_MARK(name, color, Profiling::PROFILING_CATEGORY_VIDEO_ENCODING)
#define VIDEO_ENCODING_PROFILE_PUSH_RANGE(name, color) PROFILE_PUSH_CATEGORIZED_RANGE(name, color, Profiling::PROFILING_CATEGORY_VIDEO_ENCODING)
#define VIDEO_ENCODING_PROFILE_POP_RANGE PROFILE_POP_RANGE
#define VIDEO_ENCODING_PROFILE_START_UNTHREADED_RANGE(name, color) PROFILE_START_CATEGORIZED_UNTHREADED_RANGE(name,color, Profiling::PROFILING_CATEGORY_VIDEO_ENCODING)
#define VIDEO_ENCODING_PROFILE_END_UNTHREADED_RANGE(id) Profiling::EndUnthreadedRange(id)
#define VIDEO_ENCODING_PROFILE_UNTHREADED_SCOPE(name, color) PROFILE_CATEGORIZED_UNTHREADED_SCOPE(name, color, Profiling::PROFILING_CATEGORY_VIDEO_ENCODING)
#else
#define VIDEO_ENCODING_PROFILE_SCOPE(name, color) 
#define VIDEO_ENCODING_PROFILE_SET_MARK(name, color)
#define VIDEO_ENCODING_PROFILE_PUSH_RANGE(name, color) 
#define VIDEO_ENCODING_PROFILE_POP_RANGE()
#define VIDEO_ENCODING_PROFILE_START_UNTHREADED_RANGE(name, color) 0
#define VIDEO_ENCODING_PROFILE_END_UNTHREADED_RANGE(id) id
#define VIDEO_ENCODING_PROFILE_UNTHREADED_SCOPE(name, color)
#endif


#ifdef  ALGO_PROFILING_ENABLED
#define ALGO_PROFILE_SCOPE(name, color) PROFILE_CATEGORIZED_SCOPE(name, color, Profiling::PROFILING_CATEGORY_ALGO_GENERAL)
#define ALGO_PROFILE_SET_MARK(name, color) PROFILE_SET_CATEGORIZED_MARK(name, color, Profiling::PROFILING_CATEGORY_ALGO_GENERAL)
#define ALGO_PROFILE_PUSH_RANGE(name, color) PROFILE_PUSH_CATEGORIZED_RANGE(name, color, Profiling::PROFILING_CATEGORY_ALGO_GENERAL)
#define ALGO_PROFILE_POP_RANGE PROFILE_POP_RANGE
#define ALGO_PROFILE_START_UNTHREADED_RANGE(name, color) PROFILE_START_CATEGORIZED_UNTHREADED_RANGE(name,color, Profiling::PROFILING_CATEGORY_ALGO_GENERAL)
#define ALGO_PROFILE_END_UNTHREADED_RANGE(id) Profiling::EndUnthreadedRange(id)
#define ALGO_PROFILE_UNTHREADED_SCOPE(name, color) PROFILE_CATEGORIZED_UNTHREADED_SCOPE(name, color, Profiling::PROFILING_CATEGORY_ALGO_GENERAL)
#else
#define ALGO_PROFILE_SCOPE(name, color) 
#define ALGO_PROFILE_SET_MARK(name, color)
#define ALGO_PROFILE_PUSH_RANGE(name, color) 
#define ALGO_PROFILE_POP_RANGE()
#define ALGO_PROFILE_START_UNTHREADED_RANGE(name, color) 0
#define ALGO_PROFILE_END_UNTHREADED_RANGE(id) id
#define ALGO_PROFILE_UNTHREADED_SCOPE(name, color)
#endif


#ifdef  RENDERING_PROFILING_ENABLED
#define RENDERING_PROFILE_SCOPE(name, color) PROFILE_CATEGORIZED_SCOPE(name, color, Profiling::PROFILING_CATEGORY_RENDERING)
#define RENDERING_PROFILE_SET_MARK(name, color) PROFILE_SET_CATEGORIZED_MARK(name, color, Profiling::PROFILING_CATEGORY_RENDERING)
#define RENDERING_PROFILE_PUSH_RANGE(name, color) PROFILE_PUSH_CATEGORIZED_RANGE(name, color, Profiling::PROFILING_CATEGORY_RENDERING)
#define RENDERING_PROFILE_POP_RANGE PROFILE_POP_RANGE
#define RENDERING_PROFILE_START_UNTHREADED_RANGE(name, color) PROFILE_START_CATEGORIZED_UNTHREADED_RANGE(name,color, Profiling::PROFILING_CATEGORY_RENDERING)
#define RENDERING_PROFILE_END_UNTHREADED_RANGE(id) Profiling::EndUnthreadedRange(id)
#else   
#define RENDERING_PROFILE_SCOPE(name, color) 
#define RENDERING_PROFILE_SET_MARK(name, color)
#define RENDERING_PROFILE_PUSH_RANGE(name, color) 
#define RENDERING_PROFILE_POP_RANGE()
#define RENDERING_PROFILE_START_UNTHREADED_RANGE(name, color) 
#define RENDERING_PROFILE_END_UNTHREADED_RANGE()
#endif
